import './globals.css'
import Nav from './components/Nav'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //Fetch the user
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className='mx-24'>
        <Nav expires={session?.expires as string} user={session?.user} />
        <main>{children}</main>
      </body>
    </html>
  )
}
